AllCops:
  NewCops: enable  # Enable new cops by default
  Exclude:
    - 'vendor/**/*'
    - '.lib/**/*'
    - 'config/**/*'

Layout/LineLength:
  Enabled: true

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: true

Naming/PredicateName:
  Enabled: true

Naming/AccessorMethodName:
  Enabled: true

# New cops
Gemspec/AddRuntimeDependency:
  Enabled: true

Gemspec/DeprecatedAttributeAssignment:
  Enabled: true

Gemspec/DevelopmentDependencies:
  Enabled: true

Gemspec/RequireMFA:
  Enabled: true

Layout/LineContinuationLeadingSpace:
  Enabled: true

Layout/LineContinuationSpacing:
  Enabled: true

Layout/LineEndStringConcatenationIndentation:
  Enabled: true

Layout/SpaceBeforeBrackets:
  Enabled: true

# Remove obsolete cop
# Style/BracesAroundHashParameters:  # This should be removed or commented out
