version: '3.7'

services:
  backend:
    build:
      context: .
    working_dir: /portal  # Ensure this matches the working directory where your Rails app is located
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      DATABASE_URL: "postgres://postgres:password@db:5432/rails_development"
    networks:
      - portal-network

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rails_development
    networks:
      - portal-network

networks:
  portal-network:
    name: portal
    external: true
