version: "3.9"

services:
  backend:
    build:
      context: .
    ports:
      - "3000:3000"  # Ensure backend exposes port 3000
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      DATABASE_URL: "postgres://postgres:password@db:5432/rails_development"
    networks:
      - portal-network

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rails_development
    networks:
      - portal-network

networks:
  portal-network:
    driver: bridge
