services:
  backend:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      DATABASE_URL: "postgres://postgres:password@db:5432/rails_development"
    networks:
      - portal-network

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rails_development
    networks:
      - portal-network

networks:
  portal-network:
    name: portal # Matches the external network name
    external: true # Indicates the network already exists